theme: jekyll-theme-minimal
title: [Benjamin Muller]
description: [
I'm a master studend in Data Science, interested in appying Deep Learning to general taks such as Computer Vision, Natural Language processing and Speech Recognition.
This web page aims to present my previous and current Machine Learing projects
]
